#!/usr/bin/env node
/**
 * CT-1 (24 Sep 2026): the website's pages, rendered from what the console
 * publishes.
 *
 * The site is static — GitHub Pages serves plain files, and it should stay
 * that way, because a policy page that needs an API call to render is a
 * policy page that is blank when the API is down. So the console stays the
 * single source of truth and this script is the press: it reads the live
 * text over HTTP, renders it into the site's own layout, and writes the
 * files. Publish in the console, run this, push.
 *
 *   node website/build-pages.mjs                      # against production
 *   node website/build-pages.mjs --api http://localhost:3000/api/v1
 *   node website/build-pages.mjs --check              # write nothing; say what would change
 *
 * Every page it writes carries a marker comment. A file without that marker
 * is somebody's hand-written page and is never overwritten, so the four
 * pages that exist today stay exactly as they are until their slug is
 * published from the console.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MARKER = '<!-- generated by website/build-pages.mjs — edit in the ADX console, not here -->';
const DEFAULT_API = 'https://adx-backendv1.onrender.com/api/v1';

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const at = args.indexOf(`--${name}`);
  return at >= 0 && args[at + 1] ? args[at + 1] : fallback;
};
const API = (flag('api', process.env.ADX_API_URL ?? DEFAULT_API)).replace(/\/$/, '');
const CHECK = args.includes('--check');

/**
 * The legal kinds that have a page on the website, and where each one lands.
 * A kind not named here is simply not published on the web; the apps still
 * read all thirteen.
 */
const LEGAL_PAGES = {
  PRIVACY_POLICY: 'privacy.html',
  TERMS_OF_SERVICE: 'terms.html',
  REFUND_POLICY: 'refund.html',
  CONTENT_POLICY: 'content-policy.html',
  COMMUNITY_GUIDELINES: 'community-guidelines.html',
  CODE_OF_CONDUCT: 'code-of-conduct.html',
  LEGAL_DISCLAIMER: 'disclaimer.html',
};

/* ── Markdown, the little of it a policy uses ──────────────────────── */

const escapeHtml = (text) =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Inline: links, bold, italic, code. Escaped first, so the source cannot inject HTML. */
function inline(text) {
  return escapeHtml(text)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>');
}

/**
 * Block-level Markdown: headings, unordered and ordered lists, blockquotes,
 * paragraphs. Deliberately small — a policy is prose, and anything fancier
 * belongs in the designed site rather than in a hand-rolled renderer.
 */
export function renderMarkdown(markdown) {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let list = null; // 'ul' | 'ol'
  let paragraph = [];

  const closeParagraph = () => {
    if (paragraph.length) {
      out.push(`<p>${inline(paragraph.join(' '))}</p>`);
      paragraph = [];
    }
  };
  const closeList = () => {
    if (list) {
      out.push(`</${list}>`);
      list = null;
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      closeParagraph();
      closeList();
      continue;
    }
    const heading = /^(#{1,4})\s+(.*)$/.exec(line);
    if (heading) {
      closeParagraph();
      closeList();
      const level = Math.min(heading[1].length + 1, 5); // the page's own h1 is the title
      out.push(`<h${level}>${inline(heading[2])}</h${level}>`);
      continue;
    }
    const bullet = /^[-*]\s+(.*)$/.exec(line);
    if (bullet) {
      closeParagraph();
      if (list !== 'ul') {
        closeList();
        out.push('<ul>');
        list = 'ul';
      }
      out.push(`<li>${inline(bullet[1])}</li>`);
      continue;
    }
    const numbered = /^\d+[.)]\s+(.*)$/.exec(line);
    if (numbered) {
      closeParagraph();
      if (list !== 'ol') {
        closeList();
        out.push('<ol>');
        list = 'ol';
      }
      out.push(`<li>${inline(numbered[1])}</li>`);
      continue;
    }
    const quote = /^>\s?(.*)$/.exec(line);
    if (quote) {
      closeParagraph();
      closeList();
      out.push(`<blockquote>${inline(quote[1])}</blockquote>`);
      continue;
    }
    closeList();
    paragraph.push(line);
  }
  closeParagraph();
  closeList();
  return out.join('\n    ');
}

/* ── The page ──────────────────────────────────────────────────────── */

const DATE = new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata' });

export function renderPage({ title, description, effectiveFrom, version, bodyHtml }) {
  const when = effectiveFrom ? DATE.format(new Date(effectiveFrom)) : null;
  return `<!doctype html>
${MARKER}
<html lang="en-IN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} — ADX</title>
  <meta name="description" content="${escapeHtml(description ?? '')}">
  <link rel="icon" href="brand/adx-icon-tile.svg" type="image/svg+xml">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="site">
    <div class="wrap">
      <a href="./"><img src="brand/adx-wordmark-red.svg" alt="ADX"></a>
      <nav><a href="terms.html">Terms</a><a href="refund.html">Refunds</a><a href="contact.html">Contact</a></nav>
    </div>
  </header>

  <main class="doc wrap">
    <h1>${escapeHtml(title)}</h1>
    ${when ? `<p class="meta">Effective ${when}${version ? ` · version ${version}` : ''}.</p>` : ''}
    ${bodyHtml}
  </main>

  <footer class="site">
    <div class="wrap">
      <p>© ${new Date().getFullYear()} Keysquare Technologies Pvt Ltd. <a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a> · <a href="refund.html">Refunds</a> · <a href="contact.html">Contact</a></p>
    </div>
  </footer>
</body>
</html>
`;
}

/* ── Fetching ──────────────────────────────────────────────────────── */

async function getJson(url) {
  const response = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!response.ok) throw new Error(`${url} answered ${response.status}`);
  const payload = await response.json();
  if (payload && typeof payload === 'object' && 'data' in payload) return payload.data;
  return payload;
}

/** True when the file is ours to rewrite: it does not exist, or it carries the marker. */
async function mayWrite(file) {
  try {
    const existing = await fs.readFile(file, 'utf8');
    return existing.includes(MARKER);
  } catch {
    return true;
  }
}

async function writePage(file, html, results) {
  // The site is a Next.js app now: pressed pages live in public/, served as plain files at their old addresses.
  const target = path.join(HERE, 'public', file);
  if (!(await mayWrite(target))) {
    results.skipped.push(`${file} (hand-written — publish its slug from the console to take it over)`);
    return;
  }
  let existing = null;
  try {
    existing = await fs.readFile(target, 'utf8');
  } catch {
    /* new file */
  }
  if (existing === html) {
    results.unchanged.push(file);
    return;
  }
  if (!CHECK) await fs.writeFile(target, html, 'utf8');
  results.written.push(file);
}

async function main() {
  const results = { written: [], unchanged: [], skipped: [], missing: [] };
  console.log(`Reading ${API}${CHECK ? ' (check only — nothing will be written)' : ''}`);

  // The thirteen legal documents: the ones with a page on the web.
  for (const [kind, file] of Object.entries(LEGAL_PAGES)) {
    let document;
    try {
      document = await getJson(`${API}/legal/${kind}`);
    } catch (error) {
      results.missing.push(`${kind} → ${file} (${error.message})`);
      continue;
    }
    await writePage(
      file,
      renderPage({
        title: document.title,
        description: document.summary ?? document.blurb,
        effectiveFrom: document.effectiveFrom,
        version: document.version,
        bodyHtml: renderMarkdown(document.body),
      }),
      results,
    );
  }

  // CT-1: every content page published to the website, at its own slug.
  let pages = [];
  try {
    pages = await getJson(`${API}/content?surface=WEBSITE`);
  } catch (error) {
    results.missing.push(`content index (${error.message})`);
  }
  for (const entry of pages) {
    const page = await getJson(`${API}/content/${entry.slug}`);
    await writePage(
      `${page.slug}.html`,
      renderPage({
        title: page.title,
        description: page.seoDescription,
        effectiveFrom: page.publishedAt,
        version: page.version,
        bodyHtml: renderMarkdown(page.body),
      }),
      results,
    );
  }

  const say = (label, list) => list.length && console.log(`\n${label}:\n  ${list.join('\n  ')}`);
  say(CHECK ? 'Would write' : 'Written', results.written);
  say('Unchanged', results.unchanged);
  say('Left alone', results.skipped);
  say('Not published yet', results.missing);
  console.log(
    `\n${results.written.length} ${CHECK ? 'would change' : 'written'}, ${results.unchanged.length} unchanged, ${results.skipped.length} left alone, ${results.missing.length} not published.`,
  );
}

/* Run only when invoked directly. `NODE_TEST_CONTEXT` keeps the press from
   running when Node's test runner sweeps this folder and loads the file. */
if (!process.env.NODE_TEST_CONTEXT && process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
